collections_config:
  data:
    path: "data"
  blog:
    path: "content/blog"
    output: true
    url: "content/blog/[slug]"
  pages:
    path: "content/pages"
    output: true
    url: "content/pages/[slug]"
paths:
  uploads: /images