collections_config:
  data:
    path: "data"
    label: "Profile and Settings"
  pages:
    path: "content/pages"
    output: true
    url: "/[slug]"
    _enabled_editors:
      - visual
      - content
# START COLLECTION GROUPS
collection_groups:
  - heading: Profile and Settings
    collections:
      - data
  - heading: Pages
    collections:
      - availability
      - amenities
      - architecture
      - press
      - contact
      - legal
      - neighborhood
      - residences
      - team
      - thank-you
paths:
  uploads: /images
_inputs:
  body:
    type: markdown
  logo:
    type: image