collections_config:
  data:
    path: "data"
    label: "Profile and Settings"
  pages:
    path: "content/pages"
    output: true
    url: "/[slug]"
    _enabled_editors:
      - visual
      - content
paths:
  uploads: static/images
  static: static
_inputs:
  floor_plan:
    type: image
  body:
    type: markdown
  image:
    type: image
  logo:
    type: image
  favicon:
    type: image
  photo:
    type: image
editor:
  default_path: /