collections_config:
  data:
    path: "data"
    label: "Profile and Settings"
  pages:
    path: "content/pages"
    output: true
    url: "/content/pages/[slug]"
    _enabled_editors:
      - visual
      - content
paths:
  uploads: /images
_inputs:
  body:
    type: markdown
  logo:
    type: image